apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Homelab GitOps platform project
  sourceRepos:
    - "https://github.com/mrcongliu/homelab-gitops-argocd.git" # <-- CHANGE ME
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
  roles:
    - name: read-only
      description: Read-only access for viewers
      policies:
        - p, proj:platform:read-only, applications, get, platform/*, allow
