apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-git-dir
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/example/homelab-gitops-argocd.git   # <-- CHANGE ME
        revision: HEAD
        directories:
          - path: apps/*

  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded: "true"
    spec:
      project: platform
      source:
        repoURL: https://github.com/example/homelab-gitops-argocd.git   # <-- CHANGE ME
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
